name: covid19
description: A talos app
version: 1.0.0
logLevel: DEBUG
auth:
    heimdallUrl: https://liberal-donkey.dataos.app/heimdall
    userGroups:
    - name: reader
      description: This is a reader's group
      includes:
        - roles:id:data-dev
        - roles:id:data-guru
metrics:
  type: summary
  percentiles: [ 0.5, 0.75, 0.95, 0.98, 0.99, 0.999 ]
rateLimit:
  enabled: true
  options:
    interval:
      min: 1
    max: 100
    delayAfter: 4
cachePath: tmp       
sources:
    - name: covid19test
      type: depot
